// GENERATED by tools/publish.py — do not edit by hand. Regenerate from the Excel masters.
window.ME185_DATA = {
  "meta": {
    "project": "ME-185 — The CO-OP, Erf 514, Zululami Coastal Estate",
    "client": "Collins Residential",
    "generated": "2026-07-03",
    "prepared_by": "Stefan Coetzee PrQS 4923 — Metric Edge",
    "note": "Internal working platform. The client-issued feasibility (erf-514-feasibility on Vercel, issued 12 June 2026) is frozen and is NOT modified by this system."
  },
  "contract": {
    "sections": [
      {
        "section": "Preliminaries",
        "amount": 4468919.84
      },
      {
        "section": "Building A",
        "amount": 12694874.41
      },
      {
        "section": "Building B",
        "amount": 8147822.97
      },
      {
        "section": "Building C",
        "amount": 25151861.63
      },
      {
        "section": "External Works",
        "amount": 10877466.9
      }
    ],
    "total": 61340945.75,
    "source": "ME-185 -  Final BOQ export - Main Contract - Budget.xlsx"
  },
  "psTracker": {
    "rows": [
      {
        "no": 1,
        "package": "POST-TENSIONING TO CONCRETE SLABS UNBONDED SYSTEM",
        "budget": 2133600.0,
        "afc": 2133600.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Adjudication pending",
        "subcontractor": "Pending",
        "notes": "tender figures are all in at R 1,965mil ex vat"
      },
      {
        "no": 2,
        "package": "POLISHED CONCRETE",
        "budget": 1459200.0,
        "afc": 1459200.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 3,
        "package": "PILING",
        "budget": 1340000.0,
        "afc": 1499230.0,
        "actual": 1499230.0,
        "variance": 159230.0,
        "pct_used": 1.0,
        "tender_status": "Awarded",
        "subcontractor": "Megapile",
        "notes": "this is worst as if we need CFA Piling"
      },
      {
        "no": 4,
        "package": "PLUMBING INSTALLATION TO OFFICES",
        "budget": 350000.0,
        "afc": 350000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 5,
        "package": "SANWARE/KITCHENETTES/HYDROBOILS",
        "budget": 870000.0,
        "afc": 870000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 6,
        "package": "ELECTRICAL INSTALLATION & LIFT FITTINGS",
        "budget": 4900000.0,
        "afc": 4000000.33,
        "actual": 3685836.33,
        "variance": -899999.67,
        "pct_used": 0.92,
        "tender_status": "Awarded",
        "subcontractor": "JPB",
        "notes": "this is now updated as at 3 July 2026 - appointment to JPB done at R 3,683,160.88 ex vat which includes R 334,832.81 ex vat eng contingency - tehre is a slight descrepancy with contract value -of circa R 2675.50 - refer backsheet so apointemt value is R 3,685,836.33 ex vat still with R 335,076.03 ex vat contingency and then i added another circa R 315k- kept this at R 4,000,000 to be prudent on potential overuns"
      },
      {
        "no": 7,
        "package": "ALUMINIUM DOORS & WINDOWS",
        "budget": 5200000.0,
        "afc": 5200000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Out to tender",
        "subcontractor": "Pending",
        "notes": ""
      },
      {
        "no": 8,
        "package": "ALUMINIUM SILL PLATES/F-T CAPCO DRIP SECTIONS, SLAB EDGE DETAILS AND FLASHINGS",
        "budget": 244300.0,
        "afc": 244300.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 9,
        "package": "IRONMONGERY",
        "budget": 115000.0,
        "afc": 115000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 10,
        "package": "BALUSTRADING & HANDRAILS",
        "budget": 750000.0,
        "afc": 750000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 11,
        "package": "RAINWATER GOODS",
        "budget": 300000.0,
        "afc": 300000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 12,
        "package": "HVAC/EXTRACTION",
        "budget": 4008200.0,
        "afc": 4008200.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 13,
        "package": "TIMBER PERGOLA",
        "budget": 535000.0,
        "afc": 535000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 14,
        "package": "SANITARY FITTINGS/VANITIES/GEYSERS/HEAT PUMPS & SHOWER DOORS",
        "budget": 650000.0,
        "afc": 650000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 15,
        "package": "STEEL ROOF, SHEETING,INSULATION FLASHINGS AND OTHERS ETC.",
        "budget": 2800000.0,
        "afc": 1750000.0,
        "actual": 0.0,
        "variance": -1050000.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": "based on approx R 1200/m2 ex vat"
      },
      {
        "no": 16,
        "package": "MIRRORS",
        "budget": 44000.0,
        "afc": 44000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 17,
        "package": "BATHROOM ACCESSORIES",
        "budget": 115000.0,
        "afc": 115000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 18,
        "package": "STEEL STAIRCASES & SURROUNDS",
        "budget": 630000.0,
        "afc": 630000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 19,
        "package": "TIMBER SCREENS",
        "budget": 135000.0,
        "afc": 135000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 20,
        "package": "LIFT",
        "budget": 1000000.0,
        "afc": 500000.0,
        "actual": 396650.0,
        "variance": -500000.0,
        "pct_used": 0.79,
        "tender_status": "Awarded",
        "subcontractor": "Otis",
        "notes": "Otis appointed at R 396,650 ex vat - kept R 100k ex vat for unforseens in regards to rail work etc."
      },
      {
        "no": 21,
        "package": "ROLLER SHUTTER",
        "budget": 25000.0,
        "afc": 25000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 22,
        "package": "REFUSE AREA GATE",
        "budget": 35000.0,
        "afc": 35000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 23,
        "package": "ALUMINIUM PERGOLA",
        "budget": 500000.0,
        "afc": 500000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 24,
        "package": "GENERATOR & HOUSING",
        "budget": 1000000.0,
        "afc": 900000.0,
        "actual": 0.0,
        "variance": -100000.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": "this should include the housing"
      },
      {
        "no": 25,
        "package": "WATER STORAGE & RELATED",
        "budget": 250000.0,
        "afc": 250000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 26,
        "package": "FIRE PROTECTION",
        "budget": 450000.0,
        "afc": 450000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 27,
        "package": "COURTYARD AREA STEPS AND OTHER EXTERNAL FEATURES",
        "budget": 300000.0,
        "afc": 300000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 28,
        "package": "CORNER PROTECTORS EXTERNALLY",
        "budget": 50000.0,
        "afc": 50000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 29,
        "package": "WECROLOC HANDRAILS",
        "budget": 40000.0,
        "afc": 40000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 30,
        "package": "ACCESS CONTROL",
        "budget": 300000.0,
        "afc": 300000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 31,
        "package": "LANDSCAPING",
        "budget": 1000000.0,
        "afc": 1000000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 32,
        "package": "EXTERNAL SIGNAGE",
        "budget": 100000.0,
        "afc": 100000.0,
        "actual": 0.0,
        "variance": 0.0,
        "pct_used": 0.0,
        "tender_status": "Not out",
        "subcontractor": "Not out",
        "notes": ""
      },
      {
        "no": 33,
        "package": "BULK EARTHWORKS, SERVICES & ROADS",
        "budget": 4043415.0,
        "afc": 4043415.0,
        "actual": 4043415.0,
        "variance": 0.0,
        "pct_used": 1.0,
        "tender_status": "Awarded",
        "subcontractor": "R&B Civils",
        "notes": "appoint ment made"
      }
    ],
    "total": {
      "budget": 35672715.0,
      "afc": 33281945.33,
      "actual": 9625131.33,
      "variance": -2390769.67
    },
    "source": "Zululami - Provisional Sums Tracker.xlsx"
  },
  "feasibility": {
    "lines": [
      {
        "item": "Builders & External Works",
        "nov2025": 59401469.0,
        "jun2026": 60762569.69
      },
      {
        "item": "Contingency",
        "nov2025": 2673066.1,
        "jun2026": 3825000.0
      },
      {
        "item": "Pre-Contract Escalation",
        "nov2025": 1485036.72,
        "jun2026": 0.0
      },
      {
        "item": "Contract Escalation",
        "nov2025": 2376058.76,
        "jun2026": 0.0
      },
      {
        "item": "Other Costs",
        "nov2025": 1800000.0,
        "jun2026": 2235000.0
      },
      {
        "item": "Professional Fees etc.",
        "nov2025": 7302919.36,
        "jun2026": 8355505.74,
        "detail": [
          {
            "item": "Professional Fees",
            "nov2025": 6593563.06,
            "jun2026": 7013754.35
          },
          {
            "item": "Geotech",
            "nov2025": 50000.0,
            "jun2026": 50000.0
          },
          {
            "item": "Development Management Fee",
            "nov2025": 659356.31,
            "jun2026": 1291751.39
          }
        ]
      },
      {
        "item": "Property Costs",
        "nov2025": 3350000.0,
        "jun2026": 3350000.0,
        "detail": [
          {
            "item": "Rates allowance",
            "nov2025": 250000.0,
            "jun2026": 250000.0
          },
          {
            "item": "Sectional title & body corporate fees",
            "nov2025": 1250000.0,
            "jun2026": 1250000.0
          },
          {
            "item": "Legal fee allowance",
            "nov2025": 200000.0,
            "jun2026": 200000.0
          },
          {
            "item": "Land Surveyor costs",
            "nov2025": 500000.0,
            "jun2026": 500000.0
          },
          {
            "item": "Local Authority Charges - plan scrutiny",
            "nov2025": 110000.0,
            "jun2026": 110000.0
          },
          {
            "item": "Traffic impact assessment",
            "nov2025": 40000.0,
            "jun2026": 40000.0
          },
          {
            "item": "Marketing budget",
            "nov2025": 500000.0,
            "jun2026": 500000.0
          },
          {
            "item": "Procurement letting commission",
            "nov2025": 500000.0,
            "jun2026": 500000.0
          }
        ]
      },
      {
        "item": "Finance Costs",
        "nov2025": 6114306.9,
        "jun2026": 6125189.88,
        "detail": [
          {
            "item": "Interest allowance",
            "nov2025": 4938478.65,
            "jun2026": 4947268.75
          },
          {
            "item": "Finance raising fee allowance (2%)",
            "nov2025": 1175828.25,
            "jun2026": 1177921.13
          }
        ]
      },
      {
        "item": "Land Cost",
        "nov2025": 4216777.05,
        "jun2026": 4216777.05
      },
      {
        "item": "TOTAL EXCL. VAT",
        "nov2025": 88719633.9,
        "jun2026": 88870042.36
      }
    ],
    "issued": "12 June 2026",
    "source": "Erf 514 - Revised final feasibility - June 2026.xlsx"
  },
  "appointments": [
    {
      "role": "Main Contractor",
      "firm": "Slingshot",
      "package": "Main Contract (JBCC PBA)",
      "amount": 61340946.0,
      "status": "Appointed — contract signed 12 Jun 2026",
      "instruction": "JBCC PBA - CO-OP - Slingshot"
    },
    {
      "role": "Subcontractor",
      "firm": "R&B Civils",
      "package": "Bulk Earthworks, Services & Roads",
      "amount": 4043415.0,
      "status": "Appointed",
      "instruction": "ME185-CIV-CI-01"
    },
    {
      "role": "Subcontractor",
      "firm": "Mega Pile",
      "package": "Piling",
      "amount": 1499230.0,
      "status": "Appointed",
      "instruction": "ME185-PIL-CI-01"
    },
    {
      "role": "Subcontractor",
      "firm": "JPB Electrical",
      "package": "Electrical Installation & Lift Fittings",
      "amount": 3685836.33,
      "status": "Appointed",
      "instruction": "ME185-ELE-CI-01 Rev 2"
    },
    {
      "role": "Subcontractor",
      "firm": "Otis",
      "package": "Lift",
      "amount": 396650.0,
      "status": "Appointed",
      "instruction": "ME185-LFT-CI-01"
    }
  ]
};
